package selenium;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class NewTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void newTest() {
	  
	  //driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	  String eMail="japan"+Math.random()*10+"@gmail.com";
	    driver.get("http://automationpractice.com/index.php");
	    driver.manage().window().setSize(new Dimension(1936, 1056));
	    driver.findElement(By.id("search_query_top")).click();
	    driver.findElement(By.id("search_query_top")).sendKeys("dress");
	    driver.findElement(By.id("search_query_top")).sendKeys(Keys.ENTER);
	    driver.findElement(By.xpath("//*[@id="+"'center_column'"+"]/ul/li[1]/div/div[2]/h5/a")).click();
	    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	    driver.findElement(By.xpath("//*[@id='add_to_cart']/button/span")).click();
	    driver.findElement(By.cssSelector(".button-medium > span")).click();
	    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
	    driver.findElement(By.id("email_create")).click();
	    driver.findElement(By.id("email_create")).sendKeys(eMail);
	    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
	    driver.findElement(By.id("uniform-id_gender1")).click();
	    driver.findElement(By.id("customer_firstname")).click();
	    driver.findElement(By.id("customer_firstname")).sendKeys("Mr.");
	    driver.findElement(By.id("customer_lastname")).sendKeys("Roboto");
	    driver.findElement(By.id("passwd")).click();
	    driver.findElement(By.id("passwd")).sendKeys("123456");
	    driver.findElement(By.id("email")).click();
	    driver.findElement(By.id("days")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("days"));
	      dropdown.findElement(By.xpath("//*[@id='uniform-days']")).click();
	    }
	    driver.findElement(By.id("days")).click();
	    driver.findElement(By.id("months")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("months"));
	      dropdown.findElement(By.xpath("//*[@id='months']")).click();
	    }
	    driver.findElement(By.id("months")).click();
	    driver.findElement(By.id("years")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("years"));
	      dropdown.findElement(By.xpath("//*[@id='years']")).click();
	    }
	    driver.findElement(By.id("years")).click();
	    driver.findElement(By.id("address1")).click();
	    driver.findElement(By.id("address1")).sendKeys("123 tokyo,Osaka");
	    driver.findElement(By.id("company")).click();
	    driver.findElement(By.id("company")).sendKeys("Japan");
	    driver.findElement(By.id("address2")).click();
	    driver.findElement(By.cssSelector(".is_customer_param")).click();
	    driver.findElement(By.id("address2")).click();
	    driver.findElement(By.id("address2")).sendKeys("123 Tokyo");
	    driver.findElement(By.id("city")).sendKeys("Tokyo");
	    driver.findElement(By.id("id_state")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("id_state"));
	      dropdown.findElement(By.xpath("//option[. = 'Texas']")).click();
	    }
	    driver.findElement(By.id("id_state")).click();
	    driver.findElement(By.id("postcode")).click();
	    driver.findElement(By.id("postcode")).sendKeys("00001");
	    driver.findElement(By.id("other")).click();
	    driver.findElement(By.id("other")).sendKeys("Kyoto Osaka");
	    driver.findElement(By.id("phone")).click();
	    driver.findElement(By.id("phone")).sendKeys("934232876");
	    driver.findElement(By.id("phone_mobile")).sendKeys("936452452");
	    driver.findElement(By.xpath("//*[@id='submitAccount']/span")).click();
	    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	    driver.findElement(By.xpath("//*[@id='center_column']/form/p/button/span")).click();
	    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	    driver.findElement(By.xpath("//*[@id='cgv']")).click();
	    driver.findElement(By.xpath("//*[@id='form']/p/button/span")).click();
	    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	    driver.findElement(By.xpath("//*[@id='HOOK_PAYMENT']/div[1]/div/p/a")).click();
	    driver.findElement(By.xpath(" //*[@id='cart_navigation']/button")).click();
	 
	  
  }
}
